version: "3.3"
services:
  db:
    image: "mongo"
    container_name: "mongodb_crawler"
    ports:
      - "27025:27017"
    volumes:
      - /data/mongodb:/data/db
    networks:
      - crawler-app

  app:
    build: app/
    image: marcosxaxa/daily-crawler
    container_name: daily_crawler
    networks:
      - crawler-app
    depends_on:
      - db
    environment:
      DB_URL: "db"
      DB_PORT: 27017

networks:
  crawler-app:
    driver: bridge
