name: Fetch data every 15min and save to mongodg
on:
  schedule:
    - cron: '*/15 10-19 * * 1-5'

jobs:
  fetch:
    runs-on: self-hosted
      steps:
        - name: Run daily container
          run: |
            docker run -it -d -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_NAME=${{ secrets.DB_NAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} ${{ secrets.DOCKER_HUB_USERNAME }}/daily-crawler:latest
