name: Fetch data
on:
  schedule:
  # runs from 10am to 7pm Brazil's time
    - cron: '*/55 13-22 * * 1-5'
      branches: [main]

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Run daily container
        run: |
          docker run -it -d -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_NAME=${{ secrets.DB_NAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} ${{ secrets.DOCKER_HUB_USERNAME }}/daily-crawler:latest
